In [4]:
import sys
import numpy as np

In [161]:
def part1(arr):
    heatmap = np.array([list(i) for i in arr]).astype(float)
    rollDown = np.roll(heatmap, 1, axis=0)
    rollDown[0,:] = np.inf
    rollUp = np.roll(heatmap, -1, axis=0)
    rollUp[-1,:] = np.inf
    rollRight = np.roll(heatmap, 1, axis=1)
    rollRight[:,0] = np.inf
    rollLeft = np.roll(heatmap, -1, axis=1)
    rollLeft[:,-1] = np.inf
    
    lowest = np.logical_and(np.logical_and(heatmap < rollDown, heatmap < rollUp),  np.logical_and(heatmap < rollLeft, heatmap < rollRight))
    idx = np.where(lowest)
    return np.sum(heatmap[idx]+1)

In [218]:
def calculateBasin(heatmap, x, y, visited):
    if x >= heatmap.shape[0] or x < 0 or y >= heatmap.shape[1] or y < 0 or heatmap[x,y] == False:
        return 0
    if (x,y) not in visited:
        visited.append((x,y))
        return 1 + calculateBasin(heatmap, x+1, y, visited) + calculateBasin(heatmap, x-1, y, visited) + calculateBasin(heatmap, x, y+1, visited) + calculateBasin(heatmap, x, y-1, visited)
    return 0


def part2(arr):
    heatmap = np.array([list(i) for i in arr]).astype(float)
    rollDown = np.roll(heatmap, 1, axis=0)
    rollDown[0,:] = np.inf
    rollUp = np.roll(heatmap, -1, axis=0)
    rollUp[-1,:] = np.inf
    rollRight = np.roll(heatmap, 1, axis=1)
    rollRight[:,0] = np.inf
    rollLeft = np.roll(heatmap, -1, axis=1)
    rollLeft[:,-1] = np.inf
    
    lowest = np.logical_and(np.logical_and(heatmap < rollDown, heatmap < rollUp),  np.logical_and(heatmap < rollLeft, heatmap < rollRight))
    unpeak = heatmap != 9.
    idx = np.where(lowest)
    sizes = [calculateBasin(unpeak, x,y,[]) for x,y in zip(idx[0], idx[1])]
    sizes.sort()
    return sizes[-1] * sizes[-2] * sizes[-3]

In [220]:
if __name__ == "__main__":
    file = sys.argv[-1] if sys.argv[-1].endswith(".txt") else "input.txt"
    with open(file, "r") as f:
        arr = f.read().splitlines()

        print(part1(arr))
        print(part2(arr))

444.0
[[7. 6. 7. ... 6. 7. 8.]
 [4. 5. 6. ... 5. 6. 7.]
 [5. 6. 7. ... 4. 5. 6.]
 ...
 [6. 5. 6. ... 5. 6. 7.]
 [3. 4. 5. ... 4. 7. 8.]
 [4. 5. 6. ... 5. 6. 7.]]
1168440
